### ISSUE TITLE
Projects

### ISSUE THREAD

**Issue by YakupAltay** [node101-io/library#24]
@yunus433 
@necipsagiro 
In the 'Projects' part
"node101 brings together experienced names in the blockchain world and young enthusiasts with the vision of helping the growth of the blockchain community across the globe. Feel free to reach us at support@node101.io if you have any questions/feedback on our content." (With grammar edits)
Make it like the one in https://library.node101.io/writers?lang=en

'support@node101.io' is not anchored there

**Comment by YakupAltay** [comment]
The one at https://library.node101.io/writers?lang=en 👇
Grammar edits

"node101 brings together experienced names in the blockchain world and young enthusiasts with the vision of helping the growth of the blockchain community across the globe.

Feel free to reach us at [support@node101.io](mailto:support@node101.io) if you have any questions/feedback on our content."

**Comment by necipsagiro** [comment]
#25
